# Generated by Django 5.2.5 on 2025-09-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('ua', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
