# Generated by Django 5.2.5 on 2025-09-15 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('local_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('distance_m', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('out_of_geofence', 'out_of_geofence'), ('low_accuracy', 'low_accuracy'), ('duplicate', 'duplicate'), ('blocked', 'blocked'), ('manual', 'manual')], db_index=True, default='accepted', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('web', 'web'), ('lark', 'lark'), ('pwa', 'pwa'), ('api', 'api'), ('admin', 'admin')], default='web', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=300)),
                ('lark_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checks.department')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=200)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='CheckEvent',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='checks.employee'),
        ),
        migrations.AddIndex(
            model_name='worksite',
            index=models.Index(fields=['code', 'name'], name='checks_work_code_cd52dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksite',
            constraint=models.CheckConstraint(condition=models.Q(('lat__gte', -90), ('lat__lte', 90)), name='ck_ws_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='worksite',
            constraint=models.CheckConstraint(condition=models.Q(('lng__gte', -180), ('lng__lte', 180)), name='ck_ws_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='worksite',
            constraint=models.CheckConstraint(condition=models.Q(('radius_m__gt', 0)), name='ck_ws_radius_pos'),
        ),
        migrations.AddField(
            model_name='employeeworksite',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.worksite'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checks.worksite'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['userID', 'full_name', 'department'], name='checks_empl_userID_1d9865_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeworksite',
            index=models.Index(fields=['employee', 'worksite'], name='checks_empl_employe_7e0de3_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeworksite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('employee',), name='uniq_one_default_site_per_employee'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeworksite',
            unique_together={('employee', 'worksite')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'local_date'], name='checks_atte_employe_f2d5de_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['worksite', 'ts'], name='checks_atte_worksit_ec1d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='checks_atte_status_ae4362_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('lat__gte', -90), ('lat__lte', 90)), name='ck_att_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('lng__gte', -180), ('lng__lte', 180)), name='ck_att_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('accuracy__gte', 0), ('accuracy__isnull', True), _connector='OR'), name='ck_att_acc_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('distance_m__gte', 0), ('distance_m__isnull', True), _connector='OR'), name='ck_att_dist_nonneg'),
        ),
    ]
