# Generated by Django 5.2.5 on 2025-08-26 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='code4',
            field=models.CharField(editable=False, max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Mã sản phẩm phải gồm đúng 4 chữ số.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
