# Generated by Django 5.2.5 on 2025-08-26 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_alter_product_code4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_prod_date_batch_seq',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_product_19c5a1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('product', 'import_date', 'seq')},
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_text',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='import_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='item',
            name='seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product', 'import_date'], name='inventory_i_product_ebcab6_idx'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='batch_no',
        ),
    ]
