# Generated by Django 5.2.5 on 2025-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='tag',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
