# Generated by Django 5.2.5 on 2025-08-27 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_move_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='move',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='move',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['created_at', 'action'], name='inventory_m_created_c1f75a_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['tag', 'created_at'], name='inventory_m_tag_46e83c_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['batch_id'], name='inventory_m_batch_i_563bb3_idx'),
        ),
    ]
