# Generated by Django 5.2.5 on 2025-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_move_product_move_quantity_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
