# Generated by Django 5.2.5 on 2025-09-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockorder_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='note_user',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
