"""
Django settings for warehouse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=btx$g1x8r*)1^=!3y%@b0vo=+j1@2=qovuej#7k2of=763u*%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", ".ngrok-free.app","barcode.the20.vn","*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',          # nếu cần gọi từ front-end khác domain
    'inventory',
    'drf_spectacular',
    'erp_the20',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'warehouse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'warehouse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'erp_postgres': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'erp',
        'USER': 'admin01',
        'PASSWORD': 'THE20@12345',
        'HOST': '45.76.159.161',
        'PORT': '5432',
    },
    'ecom_platform':{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecom-platform',
        'USER': 'admin01',
        'PASSWORD': 'THE20@12345',
        'HOST': '45.76.159.161',
        'PORT': '5432',
    },



}
DATABASE_ROUTERS = ['warehouse.db_routers.AppRouter']


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["x-local-access",]           # chỉ thêm dòng này]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
STATIC_ROOT = BASE_DIR / "staticfiles"


STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")



REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}



# Basic logging to see scan API logs in console during development
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        # Log our inventory app (incl. inventory.scan) at INFO
        "inventory": {"handlers": ["console"], "level": "INFO"},
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://:The20@12345@127.0.0.1:6379/1",
    }
}


# ===== Email (Gmail - hardcoded) =====
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "thinhgpt2509@gmail.com"
EMAIL_HOST_PASSWORD = "wypjupsdzulehpmz"  # App Password 16 ký tự, KHÔNG có khoảng trắng

DEFAULT_FROM_EMAIL = "thinhgpt2509@gmail.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = 20
EMAIL_SUBJECT_PREFIX = "[THE20] "



# ===== Lark / Feishu Webhook =====
# Webhook của bot trong group Lark (dạng: https://open.feishu.cn/open-apis/bot/v2/hook/XXXXX)
LARK_LEAVE_WEBHOOK_URL = "https://open.larksuite.com/open-apis/bot/v2/hook/3f29cd9b-8fd7-45a2-bdec-c9130924698c"

# (Tuỳ chọn) Map employee/manager ID -> open_id của Lark để @mention
# Muốn @ vào text: <at user_id="ou_xxx">Tên</at>
LARK_AT_MANAGER_IDS = {
    # 9001: "ou_aaaaaaaaaaaaaa",
}
LARK_AT_EMPLOYEE_IDS = {
    # 204: "ou_bbbbbbbbbbbbbb",
}

# Thời gian chờ request
LARK_TIMEOUT = 8
