# Generated by Django 4.2.24 on 2025-10-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='events',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='on_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_the20.leaverequest'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('lark', 'Lark'), ('googleforms', 'Google Forms')], default='web', max_length=16),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], default='annual', max_length=16),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee_id', 'start_date', 'end_date', 'status'], name='erp_the20_l_employe_d25645_idx'),
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
