# Generated by Django 4.2.24 on 2025-10-04 08:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0002_remove_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummaryV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('ts_in', models.DateTimeField(blank=True, null=True)),
                ('ts_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('lark', 'Lark'), ('googleforms', 'Google Forms')], default='web', max_length=16)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Tiền thưởng/bonus cho phiên làm việc (nếu có).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_valid', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('shift_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_the20.shiftinstance')),
            ],
            options={
                'ordering': ['shift_instance__date'],
            },
        ),
    ]
