# Generated by Django 5.2.5 on 2025-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0002_holidaycalendar_leavetype_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='shiftinstance',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='worksite',
            name='checkin_open_grace_min',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='checkout_grace_min',
            field=models.IntegerField(default=60),
        ),
    ]
