# Generated by Django 5.2.5 on 2025-09-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0003_remove_department_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worksite',
            name='checkin_open_grace_min',
        ),
        migrations.RemoveField(
            model_name='worksite',
            name='checkout_grace_min',
        ),
    ]
