# Generated by Django 4.2.24 on 2025-10-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0003_attendancesummaryv2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesummaryv2',
            options={'ordering': ['shift_instance__date', 'ts_in']},
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='on_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_the20.leaverequest'),
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'Onsite (Văn phòng)'), ('remote', 'Remote (Online)')], default='onsite', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancesummaryv2',
            name='shift_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_the20.shiftinstance'),
        ),
    ]
