# Generated by Django 4.2.24 on 2025-10-06 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0004_alter_attendancesummaryv2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='approved_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='requested_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesummaryv2',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancesummaryv2',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryv2',
            index=models.Index(fields=['employee_id', 'status'], name='erp_the20_a_employe_c9f534_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummaryv2',
            index=models.Index(fields=['status', 'is_valid'], name='erp_the20_a_status_41c281_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesummaryv2',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_valid', True), ('status', 'approved')), models.Q(('status', 'approved'), _negated=True), _connector='OR'), name='approved_requires_is_valid_true'),
        ),
    ]
