# Generated by Django 5.2.5 on 2025-09-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0005_alter_shiftassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_id', models.CharField(max_length=64, unique=True)),
                ('public_key_pem', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
