# Generated by Django 4.2.24 on 2025-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0005_attendancesummaryv2_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='decided_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='leave_dates_valid'),
        ),
    ]
