# Generated by Django 4.2.24 on 2025-10-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0006_leaverequest_decided_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
