# Generated by Django 5.2.5 on 2025-09-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0006_wifiverifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplate',
            name='default_worksite',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='worksite_detected',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='default_worksite',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='accuracy_m',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='distance_to_worksite_m',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='lng',
        ),
        migrations.AlterUniqueTogether(
            name='shiftinstance',
            unique_together={('template', 'date')},
        ),
        migrations.RemoveField(
            model_name='shiftinstance',
            name='worksite',
        ),
        migrations.DeleteModel(
            name='Worksite',
        ),
    ]
