# Generated by Django 5.2.5 on 2025-09-25 15:12

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0007_remove_shifttemplate_default_worksite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WifiVerifier',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='default_department',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='carry_in',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='carry_out',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='carry_over_rule',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='requires_attachment',
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='segments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='attendancecorrection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='event_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=16),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('lark', 'Lark'), ('googlefroms', 'Google Forms')], default='web', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('working_remotely', 'Working Remotely')], default='absent', max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='erp_the20.position'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_the20.shiftinstance'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='assigned', max_length=16),
        ),
        migrations.AlterField(
            model_name='shiftinstance',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='shift_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_the20.shiftinstance'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='weekly_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]), default=list, size=None),
        ),
    ]
