# Generated by Django 4.2.24 on 2025-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0007_leaverequest_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=16),
        ),
    ]
