# Generated by Django 4.2.24 on 2025-10-07 14:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0008_remove_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinstance',
            name='pay_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Hệ số lương cho ca này (vd: lễ=2.0, CN=1.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
    ]
