# Generated by Django 4.2.24 on 2025-09-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0008_delete_wifiverifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='weekly_days',
            field=models.JSONField(default=list),
        ),
    ]
