# Generated by Django 4.2.24 on 2025-09-27 08:09

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0009_alter_shifttemplate_weekly_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='weekly_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]), default=list, size=None),
        ),
    ]
