# Generated by Django 4.2.24 on 2025-10-08 05:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0009_shiftinstance_pay_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('employee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('ts_in', models.DateTimeField(blank=True, null=True)),
                ('ts_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.IntegerField(choices=[(0, 'Web'), (1, 'Mobile'), (2, 'Lark'), (3, 'Google Forms')], default=0)),
                ('work_mode', models.IntegerField(choices=[(0, 'Onsite (Văn phòng)'), (1, 'Remote (Online)')], default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tiền thưởng/bonus cho phiên làm việc (nếu có).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Canceled')], default=0)),
                ('is_valid', models.BooleanField(default=False, help_text='True khi đã duyệt hợp lệ')),
                ('requested_by', models.IntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Attendance',
                'ordering': ['date', 'ts_in'],
            },
        ),
        migrations.DeleteModel(
            name='AttendanceCorrection',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='shift_instance',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='on_leave',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryv2',
            name='on_leave',
        ),
        migrations.RemoveField(
            model_name='attendancesummaryv2',
            name='shift_instance',
        ),
        migrations.AlterUniqueTogether(
            name='shiftinstance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shiftinstance',
            name='template',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='LeaveReques_employe_9fe01b_idx',
            old_name='erp_the20_l_employe_d25645_idx',
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='holidaycalendar',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.IntegerField(choices=[(0, 'Nghỉ phép năm'), (1, 'Nghỉ không phép'), (2, 'Nghỉ ốm'), (3, 'Nghỉ chế độ hưởng nguyên lương (kết hôn, tang lễ, v.v.)'), (4, 'Tăng ca'), (5, 'Làm online'), (6, 'Đổi ca làm'), (7, 'Đi làm muộn'), (8, 'Về sớm')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='pay_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Hệ số cho ca (ví dụ: ca đêm 1.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='paid',
            field=models.BooleanField(default=False, help_text='Đơn này có được tính lương hay không.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Approved'), (2, 'Rejected'), (3, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.IntegerField(choices=[(0, 'In-app'), (1, 'Email'), (2, 'SMS')], default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['object_type', 'role'], name='ApprovalFlo_object__cfcfae_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='AuditLog_object__83e321_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='AuditLog_actor_608f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='AuditLog_created_c5dde9_idx'),
        ),
        migrations.AddIndex(
            model_name='holidaycalendar',
            index=models.Index(fields=['date'], name='HolidayCale_date_e859c9_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['leave_type'], name='LeaveReques_leave_t_366f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['to_user', 'delivered'], name='Notificatio_to_user_78dd34_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='Notificatio_channel_05d067_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['code'], name='Position_code_eb841d_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['name'], name='Position_name_dbc707_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['code'], name='ShiftTempla_code_95a7ad_idx'),
        ),
        migrations.AlterModelTable(
            name='approvalflow',
            table='ApprovalFlow',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='AuditLog',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='holidaycalendar',
            table='HolidayCalendar',
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='LeaveRequest',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
        migrations.AlterModelTable(
            name='position',
            table='Position',
        ),
        migrations.AlterModelTable(
            name='shifttemplate',
            table='ShiftTemplate',
        ),
        migrations.DeleteModel(
            name='AttendanceEvent',
        ),
        migrations.DeleteModel(
            name='AttendanceSummary',
        ),
        migrations.DeleteModel(
            name='AttendanceSummaryV2',
        ),
        migrations.DeleteModel(
            name='ShiftInstance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_the20.leaverequest'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_the20.shifttemplate'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee_id', 'date'], name='Attendance_employe_0524a8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'is_valid'], name='Attendance_status_b5d85c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['shift_template'], name='Attendance_shift_t_17e06c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['source'], name='Attendance_source_ca144a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['work_mode'], name='Attendance_work_mo_53cc61_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 1), ('is_valid', True)), models.Q(('status', 1), _negated=True), _connector='OR'), name='attn_approved_requires_is_valid_true'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(('ts_out__isnull', True), ('ts_in__isnull', True), ('ts_out__gte', models.F('ts_in')), _connector='OR'), name='attn_ts_out_gte_ts_in_when_both_set'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee_id', 'date', 'shift_template')},
        ),
    ]
