# Generated by Django 4.2.24 on 2025-10-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0010_attendance_delete_attendancecorrection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_active_department_code'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_active_position_code'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_active_shifttemplate_code'),
        ),
    ]
