# Generated by Django 4.2.24 on 2025-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0011_alter_department_code_alter_shifttemplate_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='Notificatio_to_user_78dd34_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='Notificatio_channel_05d067_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, default='', help_text='ID đối tượng liên quan (string)', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_type',
            field=models.CharField(blank=True, default='', help_text='vd: leave_request, attendance, ...', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_status_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_lark_user_id',
            field=models.CharField(blank=True, default='', help_text='open_id Lark nếu có', max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.IntegerField(choices=[(0, 'In-app'), (1, 'Email'), (2, 'SMS'), (3, 'Lark')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delivered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, help_text='Raw payload đã gửi (mask thông tin nhạy cảm)', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['to_user', 'channel', 'delivered'], name='Notificatio_to_user_ea7b92_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['object_type', 'object_id'], name='Notificatio_object__0fda07_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='Notificatio_created_eefa20_idx'),
        ),
    ]
