# Generated by Django 4.2.24 on 2025-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0011_alter_shifttemplate_weekly_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(default=20242, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
