# Generated by Django 4.2.24 on 2025-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0012_remove_notification_notificatio_to_user_78dd34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='handover_content',
            field=models.TextField(blank=True, help_text='Nội dung bàn giao (có thể null)', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='handover_to_employee_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Employee ID được bàn giao (có thể null)', null=True),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['handover_to_employee_id'], name='LeaveReques_handove_a8316a_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(('handover_to_employee_id__isnull', True), models.Q(('handover_to_employee_id', models.F('employee_id')), _negated=True), _connector='OR'), name='leave_handover_not_self'),
        ),
    ]
