# Generated by Django 4.2.24 on 2025-09-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0012_employee_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplate',
            name='weekly_days',
        ),
    ]
