# Generated by Django 4.2.24 on 2025-10-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0013_leaverequest_handover_content_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='LeaveReques_employe_9fe01b_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='LeaveReques_leave_t_366f9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='LeaveReques_handove_a8316a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='Notificatio_to_user_ea7b92_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='Notificatio_object__0fda07_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='Notificatio_created_eefa20_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='Position_code_eb841d_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='Position_name_dbc707_idx',
        ),
        migrations.RemoveIndex(
            model_name='shifttemplate',
            name='ShiftTempla_code_95a7ad_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='paid_minutes',
            field=models.IntegerField(default=0, help_text='Số phút được tính lương (đã áp hệ số/loại trừ)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_minutes',
            field=models.IntegerField(default=0, help_text='Số phút làm thực tế (đã trừ break trong ca nếu áp dụng)'),
        ),
    ]
