# Generated by Django 4.2.24 on 2025-10-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0014_remove_leaverequest_leavereques_employe_9fe01b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
    ]
