# Generated by Django 4.2.24 on 2025-10-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_the20', '0015_remove_notification_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('cccd', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('first_day_in_job', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('doc_link', models.CharField(blank=True, default='', max_length=300)),
                ('picture_link', models.CharField(blank=True, default='', max_length=300)),
                ('offer_content', models.TextField(blank=True, default='')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('degree', models.CharField(blank=True, default='', max_length=120)),
                ('old_company', models.CharField(blank=True, default='', max_length=200)),
                ('tax_code', models.CharField(blank=True, default='', max_length=32)),
                ('bhxh', models.CharField(blank=True, default='', max_length=32)),
                ('car', models.CharField(blank=True, default='', help_text='Loại xe, số xe, năm SX', max_length=200)),
                ('temporary_address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=200)),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'EmployeeProfile',
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('employee_id', models.IntegerField(db_index=True)),
                ('manager_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'Done'), (3, 'Cancelled')], default=0)),
                ('receiver_employee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'Handover',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('employee_id', models.IntegerField(db_index=True)),
                ('manager_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Resign'), (1, 'Salary Increase'), (2, 'Contribution')])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('decision_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'Proposal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.JSONField(blank=True, help_text='List[int] user_id', null=True),
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('assignee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_the20.handover')),
            ],
            options={
                'db_table': 'HandoverItem',
                'ordering': ['created_at'],
            },
        ),
    ]
